### ISSUE TITLE
Why do I have to be online to execute tests (java.net.UnknownHostException: testng.org)

### ISSUE THREAD

**Issue by AlBundy33** [testng-team/testng-eclipse#548]
### Problem Statement
If I'm not connected to the internet and want to start a Test with TestNG (Run As -> TestNG Test)
I get this exception
```
[RemoteTestNG] detected TestNG version 6.8.9
org.testng.TestNGException: java.net.UnknownHostException: testng.org
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:341)
	at org.testng.remote.AbstractRemoteTestNG.initialize(AbstractRemoteTestNG.java:137)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:98)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.net.UnknownHostException: testng.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1304)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1270)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:264)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1161)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1045)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:959)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.testng.xml.XMLParser.parse(XMLParser.java:39)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:17)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:10)
	at org.testng.xml.Parser.parse(Parser.java:168)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:311)
	... 4 more

```

### The Dependency Management tool for your project

Maven, Gradle, Ant or Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)
-> Not sure there is a testng-6.8.7.jar in the classpath of the project (for test-executions from command-line) and the eclipse-plugin is 7.4.0

### Operating System
Tested on Windows and Linux

This was also reported a while ago in #487 but closed without comment.

**Comment by missedone** [comment]
it needs to download the testng dtd file
https://testng-docs.readthedocs.io/testngxml/

![image](https://user-images.githubusercontent.com/555134/231828366-78707035-9dba-474c-b5ec-abe664d60fbc.png)

**Comment by AlBundy33** [comment]
is it possible to disable the validation?
sometimes there is just no internet available (e.g. in trains, planes, ...)

**Comment by missedone** [comment]
If you have your own TestNG suite XML file, you can remove the dtd line. Otherwise, you may define your own TestNG XML template https://testng.org/doc/eclipse.html#eclipse-workbench-preferences

**Comment by cbeust** [comment]
Don't we have an entity resolver in place, and the DTD shipped as part of
the release, which means we should never need to look it up online?

-- 
Cédric

**Comment by AlBundy33** [comment]
ok, then why should maybe try a newer version 🙂

**Comment by ThinkGo** [comment]
1. try new/latest beta version IntelliJ IDEA 2024.1 EAP (Ultimate Edition) so you have latest version and junits running but this is not Release version though
OR
2. downgrade to “IntelliJ IDEA 2022.3.3 (Ultimate Edition)”
