### ISSUE TITLE
Can you release a new testng-clipse formal version to support testng 7.8.0

### ISSUE THREAD

**Issue by popshi** [testng-team/testng-eclipse#554]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**
Hello, 

Now tesstng uplift 7.8.0 and we want to use it, but the old testng-eclipse can't support it. can we release new formal version to support testng 7.8.0. 
here is the change. 

[missedone](https://github.com/testng-team/testng-eclipse/commits?author=missedone)

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 
java.lang.NoSuchMethodError: 'void org.testng.TestRunner.<init>(org.testng.internal.IConfiguration, org.testng.ISuite, org.testng.xml.XmlTest, boolean, java.util.Collection, java.util.List)'
	at org.testng.remote.support.RemoteTestNG6_12$1.newTestRunner(RemoteTestNG6_12.java:33)
	at org.testng.remote.support.RemoteTestNG6_12$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_12.java:66)
	at org.testng.ITestRunnerFactory.newTestRunner(ITestRunnerFactory.java:52)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:720)
	at org.testng.SuiteRunner.init(SuiteRunner.java:224)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:116)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1375)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1349)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1191)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

### The Dependency Management tool for your project

- [ * ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [ * ] Linux
- [ ] OSX

**Comment by popshi** [comment]
@cbeust Could you release a formal release for testng-eclipse? Thanks.

**Comment by missedone** [comment]
@popshi 
you can install 7.8.0 from here https://github.com/testng-team/testng-eclipse-update-site, let me update the readme as well

**Comment by popshi** [comment]
@missedone ok, Thanks.
