### ISSUE TITLE
TestNG does not show up in Run Configurations in Eclipse 4.33

### ISSUE THREAD

**Issue by mpet** [testng-team/testng-eclipse#570]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: se.ericsson.jcat.jcat_eclipse_reports [456]
  Unresolved requirement: Require-Bundle: org.testng.eclipse; bundle-version="6.7.0"
    -> Bundle-SymbolicName: org.testng.eclipse; bundle-version="7.10.0.202404131040"; singleton:="true"
       org.testng.eclipse [451]
         Unresolved requirement: Require-Bundle: com.google.guava; bundle-version="[15.0.0,22.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:493)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2074)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2065)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2005)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1968)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1884)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)

### The Dependency Management tool for your project

- Maven

### Operating System
-  Linux

**Comment by missedone** [comment]
@mpet , could you share the full stack of the error/exceptions, it's hard to tell the issue with your original post.

BTW, I just tried on the latest Eclipse 4.33 Enterprise Java and Web Developer bundle package, it worked:
<img width="1038" alt="image" src="https://github.com/user-attachments/assets/330d8db8-777d-458e-a039-5d4f3e133e88">

**Comment by mpet** [comment]
@missedone 

This is the only thing I get in the .log

```
!SESSION 2024-10-25 12:06:49.318 -----------------------------------------------
eclipse.buildId=I20240914-1800.202409091524
java.version=21.0.4
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64 -data /repo/epkboha/mje_workspace

!ENTRY org.testng.eclipse 4 0 2024-10-25 12:06:52.654
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.testng.eclipse [451]
  Unresolved requirement: Require-Bundle: com.google.guava; bundle-version="[15.0.0,22.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:493)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2074)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2065)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2005)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1968)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1884)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)

!ENTRY se.ericsson.jcat.jcat_eclipse_reports 4 0 2024-10-25 12:06:52.656
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: se.ericsson.jcat.jcat_eclipse_reports [456]
  Unresolved requirement: Require-Bundle: org.testng.eclipse; bundle-version="6.7.0"
    -> Bundle-SymbolicName: org.testng.eclipse; bundle-version="7.10.0.202404131040"; singleton:="true"
       org.testng.eclipse [451]
         Unresolved requirement: Require-Bundle: com.google.guava; bundle-version="[15.0.0,22.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:493)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2074)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2065)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2005)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1968)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1884)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
```

br,

//mikael

**Comment by mpet** [comment]
@missedone can you share your testng install list so I can see the versions?

**Comment by missedone** [comment]
well, it's jus the standard JEE bundle with testng plugin

<img width="795" alt="image" src="https://github.com/user-attachments/assets/dae6749e-7f00-4361-8c77-0e0c2b8fb1b2">

**Comment by mpet** [comment]
I checked osgi view

![image](https://github.com/user-attachments/assets/e79a2df4-6db6-4085-9d85-951e5296327c)

**Comment by mpet** [comment]
@missedone  could you check which version you have of guava?

**Comment by missedone** [comment]
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/618ee012-93c4-4d11-8289-cf6ad8436648">

**Comment by mpet** [comment]
@missedone  could you share you complete plugin config so I can compare.

**Comment by mpet** [comment]
@missedone  I can also see that the users to this version is:

![image](https://github.com/user-attachments/assets/a962cf5c-2a92-4e6f-ae50-2c4a450cca08)

**Comment by missedone** [comment]
@mpet sorry for getting it back late.
since testng eclipse plugin doesn't actually rely on guava bundle, I'm going to remove the dependency declaration from the manifest.mf file https://github.com/testng-team/testng-eclipse/blob/master/testng-eclipse-plugin/META-INF/MANIFEST.MF#L34

will test it on my local soon

**Comment by mpet** [comment]
@missedone  could you please do a release of the plugin? We have users with this failure.

**Comment by missedone** [comment]
OK, done, pls try with the latest release 7.10.2.202502241629 https://testng.org/testng-eclipse-update-site/7.10.2/
